services:
  caddy:
    container_name: fanalyzer-caddy
    build:
      context: .
      target: caddy_prod
    ports:
      - "${HTTP_PORT:-4000}:80"
    volumes:
      - ./config/prod:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ssr-server

  ssr-server:
    container_name: fanalyzer-ssr-server
    build:
      context: .
      target: app_prod
    environment:
      NODE_ENV: production

volumes:
  caddy_data:
  caddy_config:
