services:
  caddy:
    container_name: fanalyzer-caddy
    build:
      context: .
      target: caddy_prod
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp
    volumes:
      - ./config/prod/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ssr-server

  ssr-server:
    container_name: fanalyzer-ssr-server
    build:
      context: .
      target: app_prod
    environment:
      NODE_ENV: production

volumes:
  caddy_data:
  caddy_config:
