# Development environment override
services:
  caddy:
    build:
      context: .
      target: caddy_dev
    environment:
      SERVER_NAME: fanalyzer-dev.localhost
    ports:
      - "443:443"

  ssr-server:
    build:
      context: .
      target: app_dev
    volumes:
      - ./:/app
