# Development environment override
services:
  caddy:
    build:
      context: .
      target: caddy_dev
    volumes:
      - ./config/dev:/etc/caddy
    ports:
      - "4200:80"

  ssr-server:
    build:
      context: .
      target: app_dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
